repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [ --allow-multiple-documents ]
      - id: check-added-large-files
  - repo: https://github.com/myint/autoflake
    rev: b330072a26bb13aea8843f8083cee5332d71f78f
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --ignore-init-module-imports
  - repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
      - id: black
        args: [ "--line-length", "79" ]
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
        # Use black profile for isort to avoid conflicts
        # see https://github.com/PyCQA/isort/issues/1518
        args: [ "--profile", "black" ]
      - id: isort
        name: isort (cython)
        types: [ cython ]
      - id: isort
        name: isort (pyi)
        types: [ pyi ]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [ "--per-file-ignores", "__init__.py:F401" ]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.1
    hooks:
      - id: bandit
        name: bandit
        args: [ "-c", ".bandit.yaml" ]
        description: 'Bandit is a tool for finding common security issues in Python code'
        entry: bandit
        language: python
        language_version: python3
        types: [ python ]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.1
    hooks:
      - id: python-safety-dependencies-check
