#######################
# Example config.yaml #
#######################
# This file contains a config example
# thought to find real estate ads
# In particular we look for an apartment
# in Milano at least tree rooms
notifications:
  title: "New ads found"
  message: |
    **Ads found found**

    You can found it [here]({{url}})
  format: markdown
  channels:
    # It is a list of apprise supported channels
    # where the scraped entities have to be sent
    - "tgram://{YOUR_BOT_TOKEN}/{CHAT_ID1}"
    - "tgram://{YOUR_BOT_TOKEN}/{CHAT_ID2}"
    - message: "Found a new adds at {{url}}"
      format: "text"
      uri: "discord://webhook_id/webhook_token"
tasks:
  # Created an entity for each site/link
  # In this case we look to two site
  - name: "immobiliare"
    # In `url`, `{i}` is a placeholder
    # for the pagination
    url: "https://www.immobiliare.it/affitto-case/milano/?criterio=rilevanza&localiMinimo=3&pag={i}"
    # `target` is a unique css selector
    # to target the <a> tag contains
    # the link to the scraped page
    target: "div.in-card.nd-mediaObject.nd-mediaObject--colToRow.in-realEstateCard.in-realEstateCard--interactive.in-realEstateListCard a.in-card__title"
    interval: 3600
  - name: "trovacasa"
    url: "https://www.trovacasa.net/Affitto/MI/Milano/index.aspx?nrlocMin=3&pag={i}"
    target: "ol#risultati li.annuncio a.js_linkdettaglio"
    interval: 3600
