version: "3"

services:
  bot-scraper:
    image: robertobochet/bot-scraper
    restart: unless-stopped
    environment:
      - BS_BOT_REDIS=redis://redis/0
    depends_on:
      - redis
    volumes:
      - "./config.yaml:/etc/bot_scraper/config.yaml"

  redis:
    image: redis:6.2.6-alpine
    restart: always
