services:
  scraper-bot:
    image: ghcr.io/robertobochet/scraper-bot
    restart: unless-stopped
    environment:
      - SB__CACHE=diskcache:/var/scraper-bot/cache
    volumes:
      - "./config.yaml:/etc/scraper-bot/config.yaml"
      - "cache:/var/scraper-bot/cache"

volumes:
  cache:
    name: cache
