version: "3"

services:
  scraper-bot:
    image: robertobochet/scraper-bot
    restart: unless-stopped
    environment:
      - BS_BOT_REDIS=redis://redis/0
    depends_on:
      - redis
    volumes:
      - "./config.yaml:/etc/scraperbot/config.yaml"

  redis:
    image: redis:6.2.6-alpine
    restart: always
